<style>

    .navbar-combo-empresa {
        
    }
  
</style>

<script>
  
//   console.log(SESSION.info.idEmpresa === '20')

  $(function(){
    //   alert(1)
  });

  Ext.onReady(function() {
    var empresa = null

    var createComboEmpresa = function(){
        Ext.create('Ext.form.ComboBox', {
            id: 'navbar-combo-empresa',
            store: Ext.create('Ext.data.Store', {
            fields: ['emp'],
                data : [
                    {"emp":"AP"},
                    {"emp":"AR"},
                    {"emp":"BH"},
                    {"emp":"BX"},
                    {"emp":"CB"},
                    {"emp":"CG"},
                    {"emp":"FZ"},
                    {"emp":"GO"},
                    {"emp":"IM"},
                    {"emp":"JF"},
                    {"emp":"JN"},
                    {"emp":"LE"},
                    {"emp":"M1"},
                    {"emp":"MA"},
                    {"emp":"MB"},
                    {"emp":"NA"},
                    {"emp":"RE"},
                    {"emp":"RJ"},
                    {"emp":"SA"},
                    {"emp":"SL"},
                    {"emp":"SN"},
                    {"emp":"TE"},
                    {"emp":"VC"}
                ]
            }),
            width: 100,
            emptyText: 'Empresa',
            margin: '8 2 2 0',
            cls: 'navbar-combo-empresa',
            fieldCls: 'browser-default navbar-combo-empresa',
            queryMode: 'local',
            displayField: 'emp',
            valueField: 'emp',
            renderTo: 'combo-empresa',
            listeners: {
                select: function(r){
                    var gridInativos = Ext.getCmp('grid-itens-inativos'),
                        gridSugestoes = Ext.getCmp('grid-itens-sugestoes')
                    
                    Ext.apply(gridInativos.getStore().proxy.extraParams, {
                        empresa: r.value
                    });

                    gridInativos.getStore().load()

                    Ext.apply(gridSugestoes.getStore().proxy.extraParams, {
                        empresa: r.value
                    });

                    gridSugestoes.getStore().load()   
                }
            }
        })
    }

    if(SESSION.info.empresa = 'EC')
    createComboEmpresa()

    // comboEmpresa.renderTo('combo-empresa')

    // Ext.create('Ext.container.Container', {
    //     layout: 'fit',
    //     width: 200,
    //     height: 38,
    //     renderTo: 'combo-empresa',
    //     items: [{
    //         xtype: 'datefield',
    //         name: 'startDate',
    //         fieldLabel: 'Start date'
    //     },{
    //         xtype: 'datefield',
    //         name: 'endDate',
    //         fieldLabel: 'End date'
    //     }]
    // });
  })

</script>

<nav class="white" role="navigation">
    <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo">Campanhas</a>
        <ul class="right hide-on-med-and-down">
            <!-- <li><a href="#">Navbar Link</a></li> -->
            <li><div id="combo-empresa"></div></li>
        </ul>
    </div>
</nav>