<!-- 
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script> -->

<!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css"/>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script> -->

<style>
  /* Extjs */
  .x-grid-item {
    font: normal 12px/14px helvetica, arial, verdana, sans-serif;
  }
  .x-grid-item td, th {
    padding: 2px 2px;
  }
</style>

<script>
  $(function(){

    $('.sidenav').sidenav();
    $('.parallax').parallax();
    $('.tabs').tabs();
    
    Ext.tip.QuickTipManager.init();
    var gridInativos = null, gridSugestoes = null;

    createFormSugestao = function(emp, codItem, descricao, preco){
      var win = Ext.create('Ext.window.Window', {
        title: 'Sugerir preço de venda',
        // height: 300,
        width: 400,
        layout: 'fit',
        // bodyPadding: 10,
        items: {
          xtype: 'form',
          layout: 'anchor',
          bodyPadding: 10,
          defaultType: 'textfield',
          defaults: {
              margin: '2 2 2 2',
              anchor: '100%'
          },
          items: [
            {
              xtype: 'fieldcontainer',
              labelWidth: 90,
              anchor: '100%',
              layout: 'hbox',
              fieldLabel: null,
              defaults: { xtype: 'textfield', hideLabel: true },
              items: [
                  {xtype: 'displayfield', name: 'emp', margin: '0 6 0 0', value: emp},
                  {xtype: 'displayfield', name: 'codItem', value: codItem, margin: '0 6 0 0'},
                  {xtype: 'displayfield', name: 'codItem', value: descricao},
              ]
            },
            // { fieldLabel: 'Preço Atual', xtype: 'displayfield', value: preco},
            { allowBlank: false, inputType: 'numberfield', xtype: 'numberfield', minValue: 0, decimalSeparator: ',', fieldLabel: 'Preço', name: 'preco', emptyText: 'Preço Ideal' },  
            { allowBlank: true, fieldLabel: 'Comentário', name: 'comentario', maxLength: 100, emptyText: 'Informações adicionais da solicitação', xtype: 'textarea' }
          ],
          buttons: [
            {
              text: 'Cancelar',
              handler: function() {
                  this.up('form').getForm().reset();
                  this.up('window').close();
              }
            }, 
            {
              text: 'Confirmar',
              formBind: true, //only enabled once the form is valid
              disabled: true,
              handler: function() {
                var me = this,
                    notyType = 'success',
                    notyText = 'Solicitação enviada com sucesso!',
                    values = me.up('form').getForm().getValues();

                    values.emp = emp
                    values.codItem = codItem
                    values.descricao = descricao

                Ext.Ajax.request({
                    url: baseUrl +'/api/campanhainativo/sugerirpreco',
                    method: 'POST',
                    params: values,
                    success: function (response) {
                        var result = Ext.decode(response.responseText);

                        if(!result.success){
                          notyType = 'error';
                          notyText = result.message;
                        }

                        new Noty({
                          theme: 'relax',
                          layout: 'bottomRight',
                          type: notyType,
                          timeout: 5000,
                          text: notyText
                        }).show();

                        me.up('form').getForm().reset();
                        me.up('window').close();
                    }
                });

              }
            }
          ]
        }
      });
      
      win.show();

      return win;
    }

    // // Ext.Ajax.cors = true;
    // Ext.Ajax.request({
    //     url: 'http://sistemas.jspecas.com.br/sistemas/public/login/index/getsession',
    //     // withCredentials: true,
    //     //      useDefaultXhrHeader: false,
    //     //      disableCaching: true,
    //     // defaultHeaders: {
    //     //     'Access-Control-Allow-Origin': '*',
    //     //     'Access-Control-Allow-Credentials': true,
    //     //     'Access-Control-Allow-Headers': 'Content-Type Authorization Accept X-Requested-With',
    //     //     'Access-Control-Allow-Methods': 'OPTIONS, TRACE, GET, HEAD, POST, PUT'
    //     // },
    //     // method: 'GET',
    //     method: 'GET',
    //     // cors: true,
    //     // useDefaultXhrHeader : false,
    //     success: function (response) {
    //         console.log(response)
    //     }
    // });

  // var invocation = new XMLHttpRequest();
  // var url = 'http://sistemas.jspecas.com.br/sistemas/public/login/index/getsession';
  // function callOtherDomain() {
  //   if(invocation) {    
  //     invocation.open('POST', url, true);
  //     invocation.setRequestHeader('Access-Control-Allow-Origin', '*');
  //     invocation.onreadystatechange = function(teste){
  //       console.log(teste)
  //     }
  //     invocation.send(); 
  //   }
  // }

  // callOtherDomain()

//     Header set Access-Control-Allow-Origin "*"
// Header set Access-Control-Allow-Headers "Content-Type Authorization Accept X-Requested-With"
// Header set Access-Control-Allow-Methods "OPTIONS, TRACE, GET, HEAD, POST, PUT"
// Header set Access-Control-Allow-Origin "https://www.google.com"

    // jQuery.support.cors = true;
    // $.ajax({
    //     url: 'http://sistemas.jspecas.com.br/sistemas/public/login/index/getsession2',
    //     type: 'GET',
    //     // crossDomain: true,
    //     success: function(data) {
    //         console.log(data);
    //     }
    // });
    
    // $.ajax({
    //   url: "http://sistemas.jspecas.com.br/sistemas/public/login/index/getsession2",
    //   crossDomain: false,
    //   success: function(data) {
    //       console.log(data);
    //   }
    // });

    // Grid de sugestões enviadas 
    
    // Ext.create('Ext.window.Window', {
    //   height: 300,
    //   width: 400,
    //   title: 'Window',
    //   scrollable: true,
    //   bodyPadding: 10,
    //   html: 'KitchenSink.DummyText.extraLongText',
    //   constrain: true,
    //   closable: false
    // }).show();
    
    // Ext.define('JS.window.SugestaoForm', {
    //     extend: 'Ext.data.Model',
    //     fields: [
    //         {name: 'COD_ITEM',  type: 'string'},
    //         {name: 'DESCRICAO',  type: 'string'},
    //         {name: 'MARCA',  type: 'string'},
    //         {name: 'ESTOQUE',  type: 'integer'},
    //         {name: 'PRECO',  type: 'number'},
    //         {name: 'BONUS',  type: 'number'}
    //     ]
    // });

    Ext.define('JS.model.ItemInativo', {
      extend: 'Ext.data.Model',
      fields: [
        {name: 'codItem',  type: 'string'},
        {name: 'descricao',  type: 'string'},
        {name: 'marca',  type: 'string'},
        {name: 'estoque',  type: 'integer'},
        {name: 'preco',  type: 'number'},
        {name: 'bonus',  type: 'number'}
      ]
    });

    gridInativos = Ext.create('Ext.grid.Panel', {
        requires: [ 'Ext.grid.column.Action' ],
        renderTo: 'grid-itens',
        id: 'grid-itens-inativos',
        minHeight: 350,
        height: Ext.getBody().getViewSize().height * 0.8,
        store: Ext.create('Ext.data.Store', {
            model: 'JS.model.ItemInativo',
            autoLoad: true,
            pageSize: null,
            proxy: {
                type: 'ajax',
                url: baseUrl+'/api/campanhainativo/listaritensinativos',
                reader: { type: 'json', rootProperty: 'data' }
            }
        }),
        
        cls: 'custom-grid',

        // stateful: true,
        multiSelect: false,
        // stateId: 'stateGrid',
        viewConfig: {
            enableTextSelection: true
        },

        columns: [
            {
                text: 'Código',
                width: 125,
                dataIndex: 'codItem'
            }, 
            {
                text: 'Descrição',
                flex: 1,
                dataIndex: 'descricao'
            }, 
            {
                text: 'Marca',
                width: 180,
                dataIndex: 'marca'
            }, 
            {
                text: 'Estoque',
                width: 90,
                dataIndex: 'estoque'
            },
            {
                text: 'Preço',
                width: 90,
                dataIndex: 'preco'
            }, {
                text: 'Bônus',
                width: 90,
                dataIndex: 'bonus'
            }, 
            {
                xtype: 'actioncolumn',
                width: 42,
                // menuDisabled: true,
                sortable: false,
                align: 'center',
                items: [{
                    tooltip: 'Sugerir preço de venda',
                    iconCls: 'far fa-comment action-icon',
                    handler: function(view, rowIndex, colIndex, item, e, record, row){  
                      // console.log(Ext.getCmp('grid-itens-inativos').getStore())
                      createFormSugestao(record.get('emp'), record.get('codItem'), record.get('descricao'), record.get('preco'));
                    }
                }]
            }
        ]
    });
    
    
    // $('#iframe-session').bind('load', function () {
    //   console.log($("#iframe-session").contents())
    // });
    
    // $('#iframe-session').load(function() {
    //     console.log($('#iframe-sessio')[0].contentWindow.$("html").html());
    // });

    // alert('teste')

  });

  // var onIframeLoad = function(){
  //   var e = document.getElementById("iframe-session");
  //   console.log(e.contentWindow.document.body.innerHTML)
      
  // }

  
</script>

<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text text-lighten-1">Parallax Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
    </div>
  </div>
  <div class="parallax"><img src="img/background1.jpg" alt="É pra vender e faturar"></div>
</div>

<div class="container">

  
  <div class="section">  

    <div class="row">

      <!--   Tabs   -->
      <ul class="tabs">
          <li class="tab col"><a class="active" href="#tab-itens">Produtos</a></li>
          <li class="tab col"><a class="active" href="#tab-sugestoes">Preços Sugeridos</a></li>
          <li class="tab col"><a href="#tab-ganhos">Meus Ganhos</a></li>
      </ul>
      
      <div id="tab-itens" class="">
        <div id="grid-itens"></div>
      </div>

      <div id="tab-sugestoes" class="">Sugestões</div> 
      <div id="tab-ganhos" class="">Ganhos</div>

    </div>

  </div>

  <div class="section">
    <!--   Icon Section   -->
    <div class="row">
      <!-- <h4>Recursos</h4> -->
      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">security</i></h2>
            <h5 class="center">Margem não afeta a comissão</h5>

            <p class="light">Se o item vendido tiver a margem menor que a sua meta de margem no mês, o item não será utilizado para calculo da remuneração.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">chat</i></h2>
            <h5 class="center">Sugestão do preço ideal de venda</h5>

            <p class="light">Aqui também é um canal de comunicação para que você possa sugerir o preço de venda ideal desses itens e não perder negócio.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">attach_money</i></h2>
            <h5 class="center">Bonificação por unidade vendida</h5>

            <p class="light">Os bônus ganhos com as vendas desses produtos serão pagos no Pega Prêmios mensalmente..</p>
          </div>
        </div>
      </div>
      

    </div>

  </div>
</div>

<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">Novas chances para novos ganhos. Aproveite.</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><img src="img/background2.jpg" alt="Novas chances para novos ganhos. Aproveite."></div>
  </div>

<footer class="page-footer orange darken-2">
    <div class="container">
        <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">Company Bio</h5>
            <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Settings</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Connect</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>