<!-- 
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.material.min.js"></script> -->
<style>
  /* Extjs */
  .x-grid-item {
    font: normal 12px/14px helvetica, arial, verdana, sans-serif;
  }
  .x-grid-item td, th {
    padding: 2px 2px;
  }
</style>

<script>
  $(function(){

    $('.sidenav').sidenav();
    $('.parallax').parallax();
    $('.tabs').tabs();
    
    // Ext.create('Ext.window.Window', {
    //   height: 300,
    //   width: 400,
    //   title: 'Window',
    //   scrollable: true,
    //   bodyPadding: 10,
    //   html: 'KitchenSink.DummyText.extraLongText',
    //   constrain: true,
    //   closable: false
    // }).show();
    
    Ext.tip.QuickTipManager.init();

    Ext.define('JS.window.SugestaoForm', {
        extend: 'Ext.data.Model',
        fields: [
            {name: 'COD_ITEM',  type: 'string'},
            {name: 'DESCRICAO',  type: 'string'},
            {name: 'MARCA',  type: 'string'},
            {name: 'ESTOQUE',  type: 'integer'}
        ]
    });

    Ext.define('JS.model.Item', {
        extend: 'Ext.data.Model',
        fields: [
            {name: 'COD_ITEM',  type: 'string'},
            {name: 'DESCRICAO',  type: 'string'},
            {name: 'MARCA',  type: 'string'},
            {name: 'ESTOQUE',  type: 'integer'}
        ]
    });

    Ext.create('Ext.grid.Panel', {
        requires: [
            'Ext.grid.column.Action'
        ],
        renderTo: 'grid-itens',
        minHeight: 350,
        height: Ext.getBody().getViewSize().height * 0.8,
        store: Ext.create('Ext.data.Store', {
            extend: 'Ext.data.Store',
            model: 'JS.model.Item',

            autoLoad: true,
            pageSize: null,

            proxy: {
                type: 'ajax',
                url: baseUrl+'/api/campanhainativo/listaritensinativos',
                reader: {
                    type: 'json',
                    rootProperty: 'data',
                    implicitIncludes: false
                }
            }
        }),
        
        cls: 'custom-grid',

        // stateful: true,
        multiSelect: false,
        // stateId: 'stateGrid',
        viewConfig: {
            enableTextSelection: true
        },

        columns: [
            {
                text: 'Código',
                width: 125,
                dataIndex: 'COD_ITEM'
            }, 
            {
                text: 'Descrição',
                flex: 1,
                dataIndex: 'DESCRICAO'
            }, {
                text: 'Marca',
                width: 180,
                dataIndex: 'MARCA'
            }, 
            {
                text: 'Estoque',
                width: 90,
                dataIndex: 'ESTOQUE'
            },
            {
                text: 'Preço',
                width: 90
            }, {
                text: 'Bônus',
                width: 90
            }, {
                xtype: 'actioncolumn',
                width: 42,
                // menuDisabled: true,
                sortable: false,
                align: 'center',
                items: [{
                    tooltip: 'Sugerir preço de venda',
                    iconCls: 'far fa-comment action-icon',
                    handler: function(view, rowIndex, colIndex, item, e, record, row){  
                      alert(record.get('COD_ITEM'))
                    }
                }]
            }
        ]
    });

  });
</script>

<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text text-lighten-2">Parallax Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="img/background.png" alt="Unsplashed background img 1"></div>
</div>


<div class="container">

  
  <div class="section">  

    <div class="row">

      <!--   Tabs   -->
      <ul class="tabs">
          <li class="tab col s2"><a class="active" href="#tab-itens">Produtos</a></li>
          <li class="tab col s2"><a class="active" href="#tab-sugestoes">Preços Sugeridos</a></li>
          <li class="tab col s2"><a href="#tab-ganhos">Meus Ganhos</a></li>
      </ul>
      
      <div id="tab-itens" class="">
        <div id="grid-itens"></div>
      </div>

      <div id="tab-sugestoes" class="">Sugestões</div> 
      <div id="tab-ganhos" class="">Ganhos</div>

    </div>

  </div>

  <div class="section">

    <!--   Icon Section   -->
    <div class="row">

      <h4>Recursos</h4>
      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>
      

    </div>

  </div>
</div>


<footer class="page-footer orange darken-2">
    <div class="container">
        <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">Company Bio</h5>
            <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Settings</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Connect</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>