<script>
  $(function(){

    $('.sidenav').sidenav();
    $('.parallax').parallax();
    $('.tabs').tabs();

  });
</script>

<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center orange-text text-lighten-2">Parallax Template</h1>
      <div class="row center">
        <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
      </div>
      <div class="row center">
        <a href="http://materializecss.com/getting-started.html" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Get Started</a>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"><img src="img/background.png" alt="Unsplashed background img 1"></div>
</div>


<div class="container">

  
  <div class="section">  

    <div class="row">

      <!--   Tabs   -->
      <ul class="tabs">
          <li class="tab col s2"><a class="active" href="#tab-itens">Produtos</a></li>
          <li class="tab col s2"><a class="active" href="#tab-sugestoes">Preços Sugeridos</a></li>
          <li class="tab col s2"><a href="#tab-ganhos">Meus Ganhos</a></li>
      </ul>
      
      <div id="tab-itens" class="">
        <table id="table-itens" class="display">
            <thead>
                <tr>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th>Marca</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Row 1 Data 1</td>
                    <td>Row 1 Data 2</td>
                    <td>Row 1 Data 3</td>
                </tr>
                <tr>
                    <td>Row 2 Data 1</td>
                    <td>Row 2 Data 2</td>
                    <td>Row 2 Data 3</td>
                </tr>
            </tbody>
        </table>
      </div>

      <div id="tab-sugestoes" class="">Sugestões</div> 
      <div id="tab-ganhos" class="">Ganhos</div>

    </div>

  </div>

  <div class="section">

    <!--   Icon Section   -->
    <div class="row">

      <h4>Recursos</h4>
      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>

      <div class="col s12 m4">
        <div class="card-panel">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Easy to work with</h5>

            <p class="light">We have provided detailed documentation as well as specific code examples to help new users get started. We are also always open to feedback and can answer any questions a user may have about Materialize.</p>
          </div>
        </div>
      </div>
      

    </div>

  </div>
</div>


<footer class="page-footer orange darken-2">
    <div class="container">
        <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">Company Bio</h5>
            <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job. Any amount would help support and continue development on this project and is greatly appreciated.</p>


        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Settings</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        <div class="col l3 s12">
            <h5 class="white-text">Connect</h5>
            <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
            <li><a class="white-text" href="#!">Link 3</a></li>
            <li><a class="white-text" href="#!">Link 4</a></li>
            </ul>
        </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
        Made by <a class="brown-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
    </div>
</footer>